name: Tag and Publish NPM Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tag-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Tag the release
        env:
          PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version}}
        run: |
          git config --local user.name "NPM Publish Bot"
          git config --local user.email "jyrone.parker@gmail.com"
          git tag "v${{ env.PACKAGE_VERSION }}"
          git push origin "v${{ env.PACKAGE_VERSION }}"

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
